version: "3.1"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
  back-tier:

services:

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "153:53/tcp"
      - "153:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Vancouver'
      WEBPASSWORD: admin
    # Volumes store your data between container upgrades
    volumes:
      - './pihole/etc/pihole/setupVars.conf:/etc/pihole/setupVars.conf'
      - './pihole/etc/pihole/custom.list:/etc/pihole/custom.list'
      - './pihole/etc/pihole/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf'
      - './pihole/etc/pihole/dhcp.leases:/etc/pihole/dhcp.leases'
      - './pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - ping:ping
      - speedtest:speedtest
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier

  ping:
    image: prom/blackbox-exporter
    tty: true
    stdin_open: true
    expose:
      - 9115
    ports:
      - 9115:9115
    restart: always
    volumes:
      - ./blackbox/config:/config
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - back-tier

  speedtest:
    image: miguelndecarvalho/speedtest-exporter
    tty: true
    stdin_open: true
    expose:
      - 9798
    ports:
      - 9798:9798
    restart: always
    networks:
      - back-tier

  nodeexporter:
    image: prom/node-exporter
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    restart: always
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier
